version: '3.8'

services:
  app:
    image: jira-slack-svc
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASS: example
      DATABASE_NAME: mydb

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
